/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SocialPostService } from "../socialPost.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SocialPostCreateInput } from "./SocialPostCreateInput";
import { SocialPost } from "./SocialPost";
import { SocialPostFindManyArgs } from "./SocialPostFindManyArgs";
import { SocialPostWhereUniqueInput } from "./SocialPostWhereUniqueInput";
import { SocialPostUpdateInput } from "./SocialPostUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SocialPostControllerBase {
  constructor(
    protected readonly service: SocialPostService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SocialPost })
  @nestAccessControl.UseRoles({
    resource: "SocialPost",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSocialPost(
    @common.Body() data: SocialPostCreateInput
  ): Promise<SocialPost> {
    return await this.service.createSocialPost({
      data: data,
      select: {
        createdAt: true,
        id: true,
        image: true,
        shortDescription: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SocialPost] })
  @ApiNestedQuery(SocialPostFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SocialPost",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async socialPosts(@common.Req() request: Request): Promise<SocialPost[]> {
    const args = plainToClass(SocialPostFindManyArgs, request.query);
    return this.service.socialPosts({
      ...args,
      select: {
        createdAt: true,
        id: true,
        image: true,
        shortDescription: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SocialPost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SocialPost",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async socialPost(
    @common.Param() params: SocialPostWhereUniqueInput
  ): Promise<SocialPost | null> {
    const result = await this.service.socialPost({
      where: params,
      select: {
        createdAt: true,
        id: true,
        image: true,
        shortDescription: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SocialPost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SocialPost",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSocialPost(
    @common.Param() params: SocialPostWhereUniqueInput,
    @common.Body() data: SocialPostUpdateInput
  ): Promise<SocialPost | null> {
    try {
      return await this.service.updateSocialPost({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          image: true,
          shortDescription: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SocialPost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SocialPost",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSocialPost(
    @common.Param() params: SocialPostWhereUniqueInput
  ): Promise<SocialPost | null> {
    try {
      return await this.service.deleteSocialPost({
        where: params,
        select: {
          createdAt: true,
          id: true,
          image: true,
          shortDescription: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
