/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PhotoGalleryService } from "../photoGallery.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PhotoGalleryCreateInput } from "./PhotoGalleryCreateInput";
import { PhotoGallery } from "./PhotoGallery";
import { PhotoGalleryFindManyArgs } from "./PhotoGalleryFindManyArgs";
import { PhotoGalleryWhereUniqueInput } from "./PhotoGalleryWhereUniqueInput";
import { PhotoGalleryUpdateInput } from "./PhotoGalleryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PhotoGalleryControllerBase {
  constructor(
    protected readonly service: PhotoGalleryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PhotoGallery })
  @nestAccessControl.UseRoles({
    resource: "PhotoGallery",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPhotoGallery(
    @common.Body() data: PhotoGalleryCreateInput
  ): Promise<PhotoGallery> {
    return await this.service.createPhotoGallery({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        photosAndVideos: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PhotoGallery] })
  @ApiNestedQuery(PhotoGalleryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PhotoGallery",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async photoGalleries(
    @common.Req() request: Request
  ): Promise<PhotoGallery[]> {
    const args = plainToClass(PhotoGalleryFindManyArgs, request.query);
    return this.service.photoGalleries({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        photosAndVideos: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PhotoGallery })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PhotoGallery",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async photoGallery(
    @common.Param() params: PhotoGalleryWhereUniqueInput
  ): Promise<PhotoGallery | null> {
    const result = await this.service.photoGallery({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        photosAndVideos: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PhotoGallery })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PhotoGallery",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePhotoGallery(
    @common.Param() params: PhotoGalleryWhereUniqueInput,
    @common.Body() data: PhotoGalleryUpdateInput
  ): Promise<PhotoGallery | null> {
    try {
      return await this.service.updatePhotoGallery({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          photosAndVideos: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PhotoGallery })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PhotoGallery",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePhotoGallery(
    @common.Param() params: PhotoGalleryWhereUniqueInput
  ): Promise<PhotoGallery | null> {
    try {
      return await this.service.deletePhotoGallery({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          photosAndVideos: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
